scan_filter_chain:
- name: left_front_pilar
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -1.4
    upper_angle: -0.896
- name: left_back_pilar
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -0.409
    upper_angle: -0.356
- name: right_front_pilar
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0.896
    upper_angle: 1.4
- name: right_back_pilar
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 0.356
    upper_angle: 0.409

# more filter options can be found: http://wiki.ros.org/laser_filters