scan_filter_chain:
- name: right_pillar
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -0.5
    upper_angle: 0

# more filter options can be found: http://wiki.ros.org/laser_filters